<?php

namespace App\Service;

use App\Exception\AppException;
use Exception;

class TokenLinkService
{
    private string $appSecret;
    private int $expirationPeriod;
    private const CIPHER = 'aes-256-cbc';

    /**
     * @param string $appSecret The secret key used for generating the links.
     * @param int $expirationPeriod Token expiration period in seconds (default is 7 days).
     */
    public function __construct(string $appSecret, int $expirationPeriod = 604800) // 7 days in seconds
    {
        $this->appSecret = $appSecret;
        $this->expirationPeriod = $expirationPeriod;
    }

    /**
     * Generates a secure link for the given email address.
     *
     * The link is a URL-safe base64 encoded string, consisting of:
     * - A SHA256 HMAC of the IV and the encrypted data
     * - The randomly generated IV
     * - The encrypted data
     *
     * The encryption algorithm used is AES-256-CBC.
     * The HMAC is used for message authentication.
     *
     * @param string $email The email address for the link
     *
     * @return string The generated link
     *
     * @throws AppException If there is an error while generating the link
     */
    public function generateLink(string $email): string
    {
        $expiration = time() + $this->expirationPeriod;
        $data = json_encode([
            'email' => strtolower(trim($email)),
            'exp' => $expiration,
            'nonce' => bin2hex(random_bytes(8)),
        ], JSON_THROW_ON_ERROR);

        $ivlen = openssl_cipher_iv_length(self::CIPHER);
        $iv = random_bytes($ivlen);

        $encKey = $this->deriveKey('lockpost-token-enc');
        $encrypted = openssl_encrypt($data, self::CIPHER, $encKey, OPENSSL_RAW_DATA, $iv);

        if ($encrypted === false) {
            throw new AppException('Failed to encrypt data');
        }

        $payload = $iv . $encrypted;
        $hmacKey = $this->deriveKey('lockpost-token-auth');
        $hmac = hash_hmac('sha256', $payload, $hmacKey, true);

        // Encode securely: (HMAC + IV + Encrypted Data)
        return rtrim(strtr(base64_encode($hmac . $payload), '+/', '-_'), '=');
    }

    /**
     * Validates a secure link generated by {@see generateLink}.
     *
     * @param string $token The secure link to validate
     *
     * @return string The email address associated with the link if it is valid
     *
     * @throws AppException If the link is invalid, corrupted, tampered with, or has expired
     */
    public function validateLink(string $token): string
    {
        try {
            // Restore URL-safe base64 to standard base64 and re-add stripped padding
            $token = strtr($token, '-_', '+/');
            $token .= str_repeat('=', (4 - (strlen($token) % 4)) % 4);

            $decoded = base64_decode($token, true);
            if ($decoded === false) {
                throw new AppException('Invalid token format');
            }

            $hmacSize = 32; // SHA256 produces 32 bytes
            $ivlen = openssl_cipher_iv_length(self::CIPHER);

            if (strlen($decoded) < ($hmacSize + $ivlen + 1)) {
                throw new AppException('Invalid token length');
            }

            $hmac = substr($decoded, 0, $hmacSize);
            $iv = substr($decoded, $hmacSize, $ivlen);
            $encrypted = substr($decoded, $hmacSize + $ivlen);

            if (empty($iv) || strlen($iv) !== $ivlen) {
                throw new AppException('Invalid or corrupted IV');
            }

            // Recalculate HMAC and validate it using a constant-time comparison
            $hmacKey = $this->deriveKey('lockpost-token-auth');
            $calculatedHmac = hash_hmac('sha256', $iv . $encrypted, $hmacKey, true);
            if (!hash_equals($hmac, $calculatedHmac)) {
                throw new AppException('Token has been tampered with');
            }

            // Decrypt the encrypted data
            $encKey = $this->deriveKey('lockpost-token-enc');
            $decrypted = openssl_decrypt($encrypted, self::CIPHER, $encKey, OPENSSL_RAW_DATA, $iv);

            if ($decrypted === false) {
                throw new AppException('Failed to decrypt data');
            }

            $data = json_decode($decrypted, true, 512, JSON_THROW_ON_ERROR);
            if (!is_array($data) || empty($data['email']) || empty($data['exp']) || !is_string($data['email']) || !is_numeric($data['exp'])) {
                throw new AppException('Invalid token data');
            }

            if ($data['exp'] < time()) {
                throw new AppException('Link has expired');
            }

            return $data['email'];
        } catch (AppException $e) {
            throw $e;
        } catch (Exception $e) {
            throw new AppException('Unable to validate token', 0, $e);
        }
    }

    /**
     * Derives a cryptographically secure, purpose-bound key from the application secret.
     *
     * @param string $info Context/purpose for HKDF key derivation
     * @return string The derived 256-bit key
     */
    private function deriveKey(string $info): string
    {
        return hash_hkdf('sha256', $this->appSecret, 32, $info);
    }

    /**
     * Returns the token expiration period in seconds.
     */
    public function getExpirationPeriod(): int
    {
        return $this->expirationPeriod;
    }
}
