<?php

namespace App\Service;

use App\Exception\AppException;
use Exception;

/**
 * Generates and validates stateless, password-protected link tokens.
 *
 * Token format (v2, AEAD):
 *   base64url("v2" + nonce[24] + ciphertext+mac)
 *
 * Token format (v1, legacy AES-256-CBC + HMAC-SHA256):
 *   base64url(hmac[32] + iv[16] + ciphertext)
 *
 * v1 tokens are still accepted for backward compatibility until they expire.
 * New tokens are always generated in v2 format.
 *
 * v2 uses XChaCha20-Poly1305 IETF (AEAD) which provides:
 * - Combined encryption + authentication (no separate HMAC needed)
 * - 24-byte nonce (nonce-misuse resistant, no collisions)
 * - Simpler code (no manual encrypt-then-MAC ordering issues)
 */
class TokenLinkService
{
    private string $tokenSecret;
    private int $expirationPeriod;

    private const CIPHER = 'aes-256-cbc';
    private const TOKEN_VERSION_V2 = 'v2';

    /**
     * @param string $appSecret The secret key used for generating the links.
     * @param int $expirationPeriod Token expiration period in seconds (default is 7 days).
     */
    public function __construct(string $appSecret, int $expirationPeriod = 604800)
    {
        $this->tokenSecret = $appSecret;
        $this->expirationPeriod = $expirationPeriod;
    }

    /**
     * Generates a secure link for the given email address (v2 AEAD format).
     *
     * @param string $email The email address for the link
     * @return string The generated link
     * @throws AppException If there is an error while generating the link
     */
    public function generateLink(string $email): string
    {
        $expiration = time() + $this->expirationPeriod;
        $data = json_encode([
            'email' => strtolower(trim($email)),
            'exp'   => $expiration,
            'nonce' => bin2hex(random_bytes(8)),
        ], JSON_THROW_ON_ERROR);

        // v2: AEAD with XChaCha20-Poly1305 IETF (24-byte nonce)
        $key = $this->deriveV2Key();
        $nonce = random_bytes(24);

        $ciphertext = sodium_crypto_aead_xchacha20poly1305_ietf_encrypt(
            $data,
            '',
            $nonce,
            $key
        );

        if ($ciphertext === false) {
            throw new AppException('Failed to encrypt data');
        }

        $payload = self::TOKEN_VERSION_V2 . $nonce . $ciphertext;

        return rtrim(strtr(base64_encode($payload), '+/', '-_'), '=');
    }

    /**
     * Validates a secure link generated by {@see generateLink}.
     *
     * Supports both v1 (AES-256-CBC + HMAC) and v2 (XChaCha20-Poly1305 IETF)
     * token formats. Version is auto-detected from the token structure.
     *
     * @param string $token The secure link to validate
     * @return string The email address associated with the link if it is valid
     * @throws AppException If the link is invalid, corrupted, tampered with, or has expired
     */
    public function validateLink(string $token): string
    {
        try {
            $token = strtr($token, '-_', '+/');
            $token .= str_repeat('=', (4 - (strlen($token) % 4)) % 4);

            $decoded = base64_decode($token, true);
            if ($decoded === false) {
                throw new AppException('Invalid token format');
            }

            // Auto-detect token version: v2 tokens start with "v2" magic bytes
            if (strlen($decoded) >= 2 && substr($decoded, 0, 2) === self::TOKEN_VERSION_V2) {
                return $this->validateLinkV2($decoded);
            }

            // Fall back to v1 (AES-256-CBC + HMAC) for backward compatibility
            return $this->validateLinkV1($decoded);
        } catch (AppException $e) {
            throw $e;
        } catch (Exception $e) {
            throw new AppException('Unable to validate token', 0, $e);
        }
    }

    /**
     * Validates a v2 (AEAD) token.
     *
     * v2 format: "v2" + nonce[24] + ciphertext
     */
    private function validateLinkV2(string $decoded): string
    {
        $nonce = substr($decoded, 2, 24);
        $ciphertext = substr($decoded, 2 + 24);

        if (strlen($nonce) !== 24) {
            throw new AppException('Invalid token format');
        }

        $key = $this->deriveV2Key();

        $plaintext = sodium_crypto_aead_xchacha20poly1305_ietf_decrypt(
            $ciphertext,
            '',
            $nonce,
            $key
        );

        if ($plaintext === false) {
            throw new AppException('Token has been tampered with');
        }

        return $this->parseTokenData($plaintext);
    }

    /**
     * Validates a v1 (AES-256-CBC + HMAC) token.
     *
     * v1 format: hmac[32] + iv[16] + ciphertext
     */
    private function validateLinkV1(string $decoded): string
    {
        $hmacSize = 32;
        $ivlen = openssl_cipher_iv_length(self::CIPHER);

        if (strlen($decoded) < ($hmacSize + $ivlen + 1)) {
            throw new AppException('Invalid token length');
        }

        $hmac = substr($decoded, 0, $hmacSize);
        $iv = substr($decoded, $hmacSize, $ivlen);
        $encrypted = substr($decoded, $hmacSize + $ivlen);

        if (empty($iv) || strlen($iv) !== $ivlen) {
            throw new AppException('Invalid or corrupted IV');
        }

        $hmacKey = $this->deriveV1Key('auth');
        $calculatedHmac = hash_hmac('sha256', $iv . $encrypted, $hmacKey, true);
        if (!hash_equals($hmac, $calculatedHmac)) {
            throw new AppException('Token has been tampered with');
        }

        $encKey = $this->deriveV1Key('enc');
        $decrypted = openssl_decrypt($encrypted, self::CIPHER, $encKey, OPENSSL_RAW_DATA, $iv);

        if ($decrypted === false) {
            throw new AppException('Failed to decrypt data');
        }

        return $this->parseTokenData($decrypted);
    }

    /**
     * Parse the JSON token data and validate its structure and expiration.
     */
    private function parseTokenData(string $plaintext): string
    {
        $data = json_decode($plaintext, true, 512, JSON_THROW_ON_ERROR);
        if (!is_array($data) || empty($data['email']) || empty($data['exp']) || !is_string($data['email']) || !is_numeric($data['exp'])) {
            throw new AppException('Invalid token data');
        }

        if ($data['exp'] < time()) {
            throw new AppException('Link has expired');
        }

        return $data['email'];
    }

    /**
     * Derives a v2 key from the application secret using HKDF.
     * Uses a different info string than v1 for key separation.
     */
    private function deriveV2Key(): string
    {
        return hash_hkdf('sha256', $this->tokenSecret, 32, 'lockpost-token-v2');
    }

    /**
     * Derives a v1 key from the application secret for backward compatibility.
     */
    private function deriveV1Key(string $purpose): string
    {
        $info = $purpose === 'auth' ? 'lockpost-token-auth' : 'lockpost-token-enc';
        return hash_hkdf('sha256', $this->tokenSecret, 32, $info);
    }

    /**
     * Backward-compatible alias for v1 key derivation.
     * Used by generateLinkV1() for testing and token rotation.
     *
     * @deprecated Use generateLink() (v2) instead. Kept for v1 token tests.
     */
    private function deriveKey(string $info): string
    {
        return $this->deriveV1Key($info === 'lockpost-token-enc' ? 'enc' : 'auth');
    }

    /**
     * Returns the token expiration period in seconds.
     */
    public function getExpirationPeriod(): int
    {
        return $this->expirationPeriod;
    }

    /**
     * Generates a v1 (legacy AES-256-CBC + HMAC) token.
     *
     * Kept for backward compatibility testing and migration scenarios.
     * New code should use generateLink() which produces v2 AEAD tokens.
     */
    public function generateLinkV1(string $email): string
    {
        $expiration = time() + $this->expirationPeriod;
        $data = json_encode([
            'email' => strtolower(trim($email)),
            'exp'   => $expiration,
            'nonce' => bin2hex(random_bytes(8)),
        ], JSON_THROW_ON_ERROR);

        $ivlen = openssl_cipher_iv_length(self::CIPHER);
        $iv = random_bytes($ivlen);

        $encKey = $this->deriveV1Key('enc');
        $encrypted = openssl_encrypt($data, self::CIPHER, $encKey, OPENSSL_RAW_DATA, $iv);

        if ($encrypted === false) {
            throw new AppException('Failed to encrypt data');
        }

        $payload = $iv . $encrypted;
        $hmacKey = $this->deriveV1Key('auth');
        $hmac = hash_hmac('sha256', $payload, $hmacKey, true);

        return rtrim(strtr(base64_encode($hmac . $payload), '+/', '-_'), '=');
    }
}
