services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - php
    restart: 'no'
    volumes:
      - ./public:/var/www/app/public

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: php
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./:/var/www/app
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./config/pgp:/var/www/app/config/pgp:delegated
    environment:
      - GNUPGHOME=/var/www/app/config/pgp
      - PHP_IDE_CONFIG=serverName=symfony
    restart: 'no'

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025" # SMTP server
      - "8025:8025" # Web interface
    restart: 'no'
