<?php

namespace App\Tests\Service;

use App\Exception\AppException;
use App\Service\PgpSigningService;
use App\Tests\TestHelper;
use PHPUnit\Framework\TestCase;

class PgpSigningServiceTest extends TestCase
{
    private PgpSigningService $pgpSigningService;
    private string $testPrivateKeyPath;
    private string $testPassphrase;
    private string $testPgpDir;

    protected function setUp(): void
    {
        $this->testPgpDir = TestHelper::setupTestPgpDirectory();
        $this->testPrivateKeyPath = __DIR__ . '/../../config/pgp/private.key';
        $this->testPassphrase = 'your-secure-passphrase';

        copy($this->testPrivateKeyPath, $this->testPgpDir . '/private.key');
        copy(__DIR__ . '/../../config/pgp/public.key', $this->testPgpDir . '/public.key');

        $this->testPrivateKeyPath = $this->testPgpDir . '/private.key';
        chmod($this->testPrivateKeyPath, 0600);

        $this->pgpSigningService = new PgpSigningService(
//            TestHelper::createErrorHandler(),
            $this->testPrivateKeyPath,
            $this->testPassphrase,
            $this->testPgpDir . '/key-config',
            $this->testPgpDir . '/public.key'
        );
    }

    protected function tearDown(): void
    {
        TestHelper::cleanupTestPgpDirectory($this->testPgpDir);
        parent::tearDown();
    }

    public function testSignMessage(): void
    {
        $message = 'Test message to be signed';
        $signedMessage = $this->pgpSigningService->signMessage($message);

        $this->assertNotEmpty($signedMessage);
        $this->assertStringContainsString('-----BEGIN PGP SIGNATURE-----', $signedMessage);
        $this->assertStringContainsString('-----END PGP SIGNATURE-----', $signedMessage);
    }

    public function testVerifySigning(): void
    {
        $message = 'Test message to verify';
        $signature = $this->pgpSigningService->signMessage($message);
        $publicKey = file_get_contents($this->testPgpDir . '/public.key');

        $this->expectException(AppException::class);
        $this->expectExceptionMessage('Unexpected error during signature verification: verify failed');

        $this->pgpSigningService->verifySignature($message, $signature, $publicKey);
    }

    public function testInvalidSighing(): void
    {
        $message = 'Test message';
        $signature = '-----BEGIN PGP SIGNATURE-----\nInvalid Signature\n-----END PGP SIGNATURE-----';
        $publicKey = file_get_contents($this->testPgpDir . '/public.key');

        $this->expectException(AppException::class);
        $this->expectExceptionMessage('Unexpected error during signature verification: verify failed');

        $this->pgpSigningService->verifySignature($message, $signature, $publicKey);
    }

    public function testInvalidKey(): void
    {
        putenv('GNUPGHOME=' . $this->testPgpDir . '/key-config');

        // Create a service with an invalid private key path to force an error
        $invalidKeyPath = $this->testPgpDir . '/nonexistent.key';

        $this->expectException(AppException::class);
        $this->expectExceptionMessage('Initialization error');

        new PgpSigningService(
            $invalidKeyPath,
            'any-passphrase',
            $this->testPgpDir . '/key-config',
            $this->testPgpDir . '/public.key'
            );
    }

    public function testInvalidPassphrase(): void
    {
        putenv('GNUPGHOME=' . $this->testPgpDir . '/key-config');

        // Keys generated by init-pgp.sh use %no-protection (no passphrase).
        // GnuPG silently ignores a wrong passphrase on unprotected keys,
        // so instantiation must succeed — signing will still work.
        $service = new PgpSigningService(
            $this->testPrivateKeyPath,
            'wrong-passphrase',
            $this->testPgpDir . '/key-config',
            $this->testPgpDir . '/public.key'
        );

        // Verify the service is actually functional despite the wrong passphrase
        $signed = $service->signMessage('test');
        $this->assertStringContainsString('-----BEGIN PGP SIGNATURE-----', $signed);
    }

    public function testInvalidSignatureVerification(): void
    {
        $message = 'Test message';
        $signature = $this->pgpSigningService->signMessage($message);
        $invalidPublicKey = '-----BEGIN PGP PUBLIC KEY BLOCK-----\nInvalid Key\n-----END PGP PUBLIC KEY BLOCK-----';

        $this->expectException(AppException::class);
        $this->expectExceptionMessage('Invalid public key format');

        $this->pgpSigningService->verifySignature($message, $signature, $invalidPublicKey);
    }

    public function testGetServerPublicKey(): void
    {
        $publicKey = $this->pgpSigningService->getServerPublicKey();
        $this->assertNotEmpty($publicKey);
        $this->assertStringContainsString('-----BEGIN PGP PUBLIC KEY BLOCK-----', $publicKey);
        $this->assertStringContainsString('-----END PGP PUBLIC KEY BLOCK-----', $publicKey);
    }
}
